env:
    contexts:
    -
        excludePaths: []
        includePaths:
        - https://ebudget.taspen.co.id.*
        name: Default Context
        technology:
            exclude: []
        urls:
        - https://ebudget.taspen.co.id
    vars: {}
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
jobs:
-
    parameters:
        scanOnlyInScope: true
        enableTags: false
    rules: []
    name: passiveScan-config
    type: passiveScan-config
-
    parameters:
        context: Default Context
        maxDuration: 0
        maxDepth: 0
        maxChildren: 0
    name: spider
    type: spider
-
    parameters:
        context: Default Context
        maxDuration: 60
        maxCrawlDepth: 10
        numberOfBrowsers: 4
        runOnlyIfModern: false
    name: spiderAjax
    type: spiderAjax
-
    parameters: {}
    name: passiveScan-wait
    type: passiveScan-wait
-
    parameters:
        context: Default Context
        threadPerHost: 4
    policyDefinition:
        rules: []
    name: activeScan
    type: activeScan
-
    parameters:
        template: traditional-pdf
        reportDir: ''
        reportTitle: ZAP Scanning Report
        reportDescription: ''
    name: report-pdf
    type: report
